### ISSUE TITLE
"platform?" bug after ugprading newrelic version 

### ISSUE THREAD

**Issue by shaiguitar** [djoos-cookbooks/newrelic#396]
After upgrading version 2.41.0 to 2.43.0 it looks like this bug is rearing it's head:

```
[2021-03-14T12:40:21+00:00] ERROR: Running exception handlers
[2021-03-14T12:40:21+00:00] ERROR: Exception handlers complete
[2021-03-14T12:40:21+00:00] FATAL: Stacktrace dumped to /tmp/chef/conf/local-mode-cache/cache/chef-stacktrace.out
[2021-03-14T12:40:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-03-14T12:40:21+00:00] ERROR: undefined method `platform?' for #<Class:0x0000000003038ad8>
[2021-03-14T12:40:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

No other cookbooks in this chef run were changed but the aforementioned newrelic version. The chef client running this is:

```
$ chef-client --version
Chef: 13.8.5
```

https://github.com/djoos-cookbooks/newrelic/compare/0e793438ac7a6aeb53f8174473f78137cff20949..master has some references to `platform?` so I wonder if that is the correlation.

**Comment by nickdallamora** [comment]
Also had problems, related issue here: https://github.com/djoos-cookbooks/newrelic/issues/395

**Comment by djoos** [comment]
Could you give v2.43.1 a go? Thanks in advance!
